### ISSUE TITLE
REST endpoint doesn't return any tables for a controller's address

### ISSUE THREAD

**Issue by dtbuchholz** [tablelandnetwork/go-tableland#187]
### User Story
When I call the `/chain/{chainId}/tables/controller/{address}` endpoint, I expect a response of an array of objects where each object represents a table controlled at the path param `address`. However, when calling this endpoint using a smart contract address that implements `TablelandController` and has been set as the controller for a table, the results are empty.

### Steps to Reproduce
_The following was performed on Goerli (chainId: `5`)_
1. Create a table
2. Deploy a smart contract that implements `TablelandController` ([allow all example](https://github.com/tablelandnetwork/evm-tableland/blob/main/contracts/test/TestAllowAllTablelandController.sol) from the `evm-tableland` repo)
3. Call `setController` on the `TablelandTables` deployed smart contract with the address from (2) and the table from (1)
4. Insert data into the table with a random wallet, which _should_ be able to due to the allow all contract (this works as expected)
5. Call the REST API at endpoint `/chain/{chainId}/tables/controller/{address}` -- here, the response is empty, i.e., `[]`
6. Validate the controller address is the controller by calling `getController` on the registry smart contract with the tableId from (1), which should match the address from (2)

Here's an example that does the steps above:
1. See table `rest_api_5_85` (created at tx: [`0xf8da1143d65fde76c3a175685810146ea32d6695af76cf1d77758e879abaa321`](https://goerli.etherscan.io/tx/0xf8da1143d65fde76c3a175685810146ea32d6695af76cf1d77758e879abaa321))
2. See the deployed controller contract at address [`0x627A289FDfFA63b662FC52FE8b30b479B8AED2a8`](https://goerli.etherscan.io/address/0x627A289FDfFA63b662FC52FE8b30b479B8AED2a8), which simply implements the provided allow all contract in the `evm-tableland` repo (link above in step 2)
3. Calling `setController` with the address above on the [Tableland registry contract for Goerli](https://goerli.etherscan.io/address/0xda8ea22d092307874f30a1f277d1388dca0ba97a#readProxyContract) -- tx hash: [`0x83f1f3204cc8df3b4e27789579bbf485af566cbaa1a26bc2cf8f2c1556989c69`](https://goerli.etherscan.io/tx/0x83f1f3204cc8df3b4e27789579bbf485af566cbaa1a26bc2cf8f2c1556989c69)
4. Insert data with a random account, successfully -- tx hash: [`0x880b05171f22930f55c5099e7115c434f6f299abf982b2258c1bf77f6838364a`](https://goerli.etherscan.io/tx/0x880b05171f22930f55c5099e7115c434f6f299abf982b2258c1bf77f6838364a)
5. Make a GET request at the address in (2), which _incorrectly returns nothing_ (i.e., this _is_ the controller of  `rest_api_5_85` but the API says otherwise and returns `[]`): `curl 'https://testnet.tableland.network/chain/5/tables/controller/0x627A289FDfFA63b662FC52FE8b30b479B8AED2a8'` 
6. Lastly, check the registry smart contract using `getController`, passing `85`, which does return `0x627A289FDfFA63b662FC52FE8b30b479B8AED2a8` as the table's controller -- validating that (6) does not work as expected

**Comment by dtbuchholz** [comment]
I'm not sure if this is a "bug" per se, but it definitely deviates from what I would expect as a user based on the URI naming convention. Perhaps that's the issue? For reference, the CLI uses this endpoint in its `list` method, which seems like it's more catered to "show me all tables that this address owns" vs "show me all tables that this address is the controller of"

**Comment by joewagner** [comment]
Thanks for pointing this out, its always good to get a fresh perspective on this kind of thing.
The endpoint naming is a bit confusing now that we added the idea of a controller contract, but that endpoint returns the tables owned by a given wallet address. It is used internally by the js sdk `list` method.  The url  was chosen before the term "controller" had the meaning it now does in the contract.

example: If you replace the contract address with the address of the wallet that created the table you will see the tables owned by that wallet:
https://testnet.tableland.network/chain/5/tables/controller/0x4d5286d81317e284cd377cb98b478552bbe641ae

I think the endpoint as it is has been very useful for developing apps so far, but maybe we need to reconsider the naming?
RE adding another endpoint for the contract's `_controllers`: Do we have any use-cases for getting all the tables that have a given controller value?

**Comment by dtbuchholz** [comment]
Thanks for that context, makes sense -- I suppose the best outcome is what you've pointed out: a new name. If the SDK and CLI use `list`, that seems like the easiest path forward. So, i'd propose `controller` is changed to `list`:
* `/chain/{chainId}/tables/list/{address}`

...which does exactly what it describes: `tables/list/{address}` == go to tables, list at address. I suppose additional query params could be helpful here as well (out of scope but worth considering). For example, `?data=id` since the `/chain/{chainID}/tables/{id}` endpoint requires the `id` param (which must be parsed from the `/chain/{chainId}/tables/list/{address}` response `name` field). Or, maybe `id` could just be added to the `/chain/{chainId}/tables/list/{address}` response itself.

**Comment by dtbuchholz** [comment]
As for the second question re: adding an endpoint for controllers. I suppose one explanation would be similar rationale as the following: why did we add a `getController` method on the smart contract? Albeit, this has smart contract related value/implications so probably isn't the best answer for you.

Another point -- in the setup I described, I _had_ to leverage the `getController` smart contract call to verify that the controller contract was actually the controller. I have no way of doing this with the API, which means the I'm forced to use some other library or avenue to validate this information. That's not ideal if I live in REST-API-only world. The easiest path forward for this is to add `controller` (the _actual_ controller) to the response itself while adding a field for the `owner` of the table.

It does bring up the question: will a controller ever have more than one table? I think the answer is yes -- I imagine a world in the near future where we deploy the "common" controller contracts to allow for the SDK/CLI or SC devs to leverage standard ACLs (e.g., the allow all contract). Does it make sense to have an API for getting the tables that a controller is "managing"? I'm indifferent, assuming the proposed change below is accepted.

And on that note, the proposed response -- change `controller` to `owner` and add the _actual_ controller. E.g., from the example provided:
```
[
  {
    "controller": "0x4D5286d81317E284Cd377cB98b478552Bbe641ae", // i.e. this is not the controller, but the owner
    "name": "rest_api_5_85",
    "structure": "7d5cd636b3cb913155fe97a54af38383c2a7a94c98369616bdfe6409558cc57a",
    "created_at": "2022-07-17T04:57:40Z"
  }
]
```
should actually be:
```
[
  {
    "owner": "0x4D5286d81317E284Cd377cB98b478552Bbe641ae",
    "controller": "0x627A289FDfFA63b662FC52FE8b30b479B8AED2a8",
    "name": "rest_api_5_85",
    "structure": "7d5cd636b3cb913155fe97a54af38383c2a7a94c98369616bdfe6409558cc57a",
    "created_at": "2022-07-17T04:57:40Z"
  }
]
```
...which _might_ also include an `id` field, too (if that makes sense to add)

**Comment by joewagner** [comment]
>  why did we add a getController method on the smart contract? Albeit, this has smart contract related value/implications so probably isn't the best answer for you.

The get controller method was added to enable the Validator to find the controller of a single table and then call the `getPolicy` method on that contract.  Once the Validator has these results it will use them to determine, if it should, or how to run the sql statement in the runSQL event.

> I had to leverage the getController smart contract call to verify that the controller contract was actually the controller. I have no way of doing this with the API, which means the I'm forced to use some other library or avenue to validate this information.

This PR is related. https://github.com/tablelandnetwork/js-tableland/pull/81
Once it's worked out people will be able to use the SDK, or RPC API.  I haven't heard any use-cases, aside from Validators calling the contract, for calling `getController`.  I'm guessing there are some, but if you think of any specifics I'd be interested to hear them.

**Comment by sanderpick** [comment]
getController is just an informative endpoint to see what the controller of a contract is. Validator doesn’t use it for access control. Validator doesn’t read state from the chain outside of the event stream.

**Comment by sanderpick** [comment]
Ie, once in the CLI we can have a command to show the controller of a table. Actually we should have a get owner command as well… and maybe even the ability to transfer the table ownership right from the CLI

**Comment by joewagner** [comment]
> getController is just an informative endpoint to see what the controller of a contract is. Validator doesn’t use it for access control. Validator doesn’t read state from the chain outside of the event stream.

oops, I was wrong here good callout.

**Comment by dtbuchholz** [comment]
Ooh, nice, yeah that `getController ` PR will be a great addition, solves for what I'm looking for, too. And i'll open a PR re: transfer -- that was a dev request actually, recently...to help burn tables the dev doesn't want/need.

One thing to note -- generally, I think I've been coming at things with the mindset: unified experience, irrespective of if a user is in the SDK/CLI/REST/RPC. I think that's probably the wrong way to view things, so any pointers there may be helpful. E.g., with my idea around a REST endpoint for `getController` , I'm asking for something that doesn't seem to fit in the REST/RPC realm/use case and feels more like it belongs only in the SDK/CLI.

Maybe it's simple: REST/RPC for information pertinent to Tableland validators, and SDK/CLI for accessing the REST/RPC methods in addition to onchain/SC methods?

**Comment by carsonfarmer** [comment]
Where did we land here folks? Is there any interest in updating the API name to list here? Also, to answer @dtbuchholz's question about, I don't think it makes sense to add a getController REST API endpoint here, instead, we have those methods on the SDK/CLI. The REST API should really just be about simple listing, getting, and querying tables and their schemas. Anything else around access control etc should go through the RPC or SDKs.

**Comment by dtbuchholz** [comment]
@carsonfarmer I don't believe we ever came to a conclusion on this. I personally do think changing the endpoint to `list` would be worthwhile, though, since `controller` is misleading. And if this idea is accepted, then it suggests we would also want to change the response body and swap `controller` for `owner` (or similar), which adds some more complexity, I'd imagine.
