### ISSUE TITLE
Use snake case for `errorEventIdx` in `tableland_getReceipt`

### ISSUE THREAD

**Issue by dtbuchholz** [tablelandnetwork/go-tableland#222]
## Description
A small nit -- I'm not sure if there is a reason why camelcase was used for `errorEventIdx` (part of `tableland_getReceipt` response), so if so, nbd. But, for consistency across the other RPC fields (which all use snake case), the `errorEventIdx` should instead be `error_event_idx`.

**Comment by jsign** [comment]
It should already be snake case; here's a test:
```
code curl --location --request POST 'https://testnet.tableland.network/rpc' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ....' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "tableland_getReceipt",
    "id" : 69,
    "params": [{
        "txn_hash": "0x776625eeafee64e25082a325602d578ef3b3d33b93f2c757094c04d65c685bce"
    }]
}'
{"jsonrpc":"2.0","id":69,"result":{"ok":true,"receipt":{"chain_id":69,"txn_hash":"0x776625eeafee64e25082a325602d578ef3b3d33b93f2c757094c04d65c685bce","block_number":4769835,"table_id":"1","error":"","error_event_idx":-1}}}
```

I wonder where are you seeing this?

**Comment by dtbuchholz** [comment]
Ah, looks like I mixed some things up when i was testing out a PR for the CLI. I was looking at the CLI's `receipt` response (which uses camelcase) in one window while thinking it was the response from `tableland_getReceipt`. Human error, my b.

Closing this out.
