### ISSUE TITLE
The SIWE message `domain` field does not match spec

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/go-tableland#235]
The SIWE spec defines the message `domain` field as being a [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986) URI.  We are [currently enforcing](https://github.com/tablelandnetwork/go-tableland/blob/main/internal/router/middlewares/authentication.go#L21) that the value be set to "Tableland" which is not an RFC 3986 URI compliant value.
After re-reading the siwe spec we should potentially ignore the value of `domain` and start checking that the value of the message `uri` field matches the config attribute in the validator with the DNS where the gateway is served.
This change will be breaking for any one using the js sdk <= 3.1.x, and as suggested in https://github.com/tablelandnetwork/js-tableland/pull/112 by @jsign we should potentially enable accepting both message formats for some period to allow clients to update their SDK versions gracefully.

**Comment by joewagner** [comment]
Any changes here will need to have corresponding changes in the [js sdk](https://github.com/tablelandnetwork/js-tableland/blob/main/src/lib/token.ts#L29) and the [go client](https://github.com/tablelandnetwork/go-tableland/blob/main/pkg/siwe/siwe.go#L25)

**Comment by carsonfarmer** [comment]
Closing this as no longer relevant. @joewagner please reopen if we still need to fix this.

**Comment by joewagner** [comment]
Looks good, this is irrelevant now.
