### ISSUE TITLE
Add CODEOWNER file

### ISSUE THREAD

**Issue by jsign** [tablelandnetwork/go-tableland#293]
We need to add a CODEOWNER file to indicate the DRI of the repo.

**Comment by jsign** [comment]
@brunocalza, I think we both should be the DRI in reality since both can do a triage of issues and organize things in this repo.
If you think it's fine, I can be "formally" the DRI, but in practice, feel free to do triaging or any organization.

This is relevant only for backlog issues since other enhancements/features will usually be part of GH Projects with their own DRI.

LMK your thoughts!

**Comment by carsonfarmer** [comment]
What about listing _all_ relevant CODEOWNERS, with the practice that the Primary DRI is always listed first?

**Comment by jsign** [comment]
> What about listing _all_ relevant CODEOWNERS, with the practice that the Primary DRI is always listed first?

SGTM

**Comment by brunocalza** [comment]
Sounds good! :)
