### ISSUE TITLE
Add a PR template

### ISSUE THREAD

**Issue by jsign** [tablelandnetwork/go-tableland#294]
It would be useful to add a PR template, so we always have a suggested structure for PRs.

I think we've already experimented with some ideas in the latest PRs, so we can be inspired on those plus get ideas from other repos.

**Comment by carsonfarmer** [comment]
All the JS repos have a pretty extension PR template. Please feel free to use those. If you go with anything more elaborate, or better in any way, please consider PR'ing the improvements to those repos, or creating a ticket suggesting an update?
