### ISSUE TITLE
[GOT-57] List method for tables across chains

### ISSUE THREAD

**Issue by awmuncy** [tablelandnetwork/go-tableland#297]
It looks like the list endpoint requires a chain parameter. I'd like to to be able to run a single request to get all of my tables across all support chains. 

<sub>[GOT-57](https://linear.app/tableland/issue/GOT-57/list-method-for-tables-across-chains)</sub>

**Comment by brunocalza** [comment]
Looks like this was a request on the old API. Is this still something that we need? @awmuncy

**Comment by awmuncy** [comment]
No, we can get rid of this.
