### ISSUE TITLE
Allow a fresh validator to sync from a snapshot URL

### ISSUE THREAD

**Issue by jsign** [tablelandnetwork/go-tableland#303]
Our cloud validator is creating snapshots of its database with some frequency.
This is useful for many things, but in particular, it can be the basis to allow a validator to sync from a trusted/verified point in time forward.

Some obvious use-cases for this:
- Spinning a second cloud validator quickly.
- Allowing external validators to have a synced validator within less time and with fewer costs than syncing from scratch.
- Have a local validator up and synced as fast as possible for local debugging.

I'm pretty sure we need to do some extra work in the backup databases since they contain data in some tables that shouldn't be there. For example, we still copy the relayed transactions table, etc.

As part of uploading the database backups to some cloud storage to have a public URL, we can have a previous step of cleaning up information that shouldn't be there. But we can also fine-tune the backup process to generate this database directly.

Open to comments, it might require some more dedicated scoping.

**Comment by jsign** [comment]
@brunocalza, another idea that popped in my mind is that it might be fine to keep the backup with all the data and simply copy "the right things" when loading it.

That might be useful so a validator can use a simple full backup from any place, and the loading process will copy only the relevant tables. (e.g., we could even have flags to only load specific chain_id data).

Just capturing a thought here.

**Comment by brunocalza** [comment]
@jsign By relayed transactions table you mean the `system_pending_tx` table? Any other table you think copying would not be needed (I'm not seeing any others, or maybe I'm not fully getting what you mean by "data in some tables that shouldn't be there")?

I prefer the idea of letting the load process "choose the data" :) 

I guess the **simplest approach** to the load process is:
- download file
- uncompress it
- copy to the right location and rename it to `database.db`

Adding the capability of choosing the data means we would have to probably transform the backup file into a dump of SQL statements. From the dump, we would have to select only the statements of interest. Does that make sense? 

I'll probably break this work into parts:
- Simple load process (this work is what we most need)
- Automatic upload process of backup files to storage
- Enhance the load process by adding the capability of choosing which data to load

**Comment by jsign** [comment]
> @jsign By relayed transactions table you mean the `system_pending_tx` table? Any other table you think copying would not be needed (I'm not seeing any others, or maybe I'm not fully getting what you mean by "data in some tables that shouldn't be there")?

Yes, `system_pending_tx` is one of them. I think the other two are `system_evm_events` and `system_evm_blocks` which aren't _strictly_ needed, but it doesn't hurt to copy them. No strong opinions there, maybe could be optional.

> Adding the capability of choosing the data means we would have to probably transform the backup file into a dump of SQL statements. From the dump, we would have to select only the statements of interest. Does that make sense?

I see two options that might not require transforming the backup into an SQL dump.

The first is, instead of copying the backup as the base `database.db`, we could:
- Only copy data from system tables using `chain_id` conditions.
- Only copy user-tables with names that match the name `*_<chainID>_*`.
So that means doing `insert into selects` with the right `where`, and copying user-tables with name matches.

The second option, is copying `database.db` and do the inverse and delete chains we don't want.

To be clear, this requires some extra work that I'm not sure is worth it now. For example, we have to copy data in the right order to be good with FK (or disable FKs, copy the data, and then enabling that after).

I'm fine with copying the `database.db` and don't offer the option of only "importing" a subset of chain ids, since that saves a lot of work and probably nobody will be interested in that now.

LMK if it makes sense.
 
> I'll probably break this work into parts:
> 
> * Simple load process (this work is what we most need)
> * Automatic upload process of backup files to storage
> * Enhance the load process by adding the capability of choosing which data to load

:+1:
