### ISSUE TITLE
Move the analytics database and related infra to BigQuery

### ISSUE THREAD

**Issue by jsign** [tablelandnetwork/go-tableland#307]
Following a suggestion by @brunocalza, we should have some ETL or decided process to move the analytics database information living in the SQLite validator to BigQuery.

This is much nicer since:
- Retool has a native interface against BigQuery, so we don't need to run `postlite`  in the validator VM to act as a reverse proxy to give a Postgres wire-protocol support for SQLite. Also, it potentially means removing firewall rules to let Retool access the VM.
- Analytics read load won't hit the validator, prioritizing syncing chains and serving read queries.
- We'd have easier access to analytics information for the team and community by directly accessing the BQ database to do ad-hoc queries.

**Comment by brunocalza** [comment]
We can easily make a batch ETL pipeline that takes the backup file we have in GCS and load them into BQ. But that means we'll have data at most 4 hours old. 

Having a live copy of the validator's data into BQ (streaming ETL), requires a bit more thinking. 

Maybe we can start with 1).

**Comment by jsign** [comment]
Yes, having a four hours delay would be a bit annoying for a live dashboard. 

My take is that we should think about the streaming ETL idea and just leave things as they are until we do that. I'm not sure it is worth doing an intermediate step.

The streaming ETL could simply know which is the last `block_number` per chain in BQ, and do some `select * from system_evm_events where chain_id=x and block_number>y limit z`. It could be a simple Go program, or some `cron` command with a mix of `bq+sqlite3`, which I think it's pretty doable/easy.
