### ISSUE TITLE
Design a process to publish, announce and document new releases

### ISSUE THREAD

**Issue by jsign** [tablelandnetwork/go-tableland#308]
Currently, we don't have any process in the validator regarding:
- Tagging new versions.
- Generating publicly usable infra assets (docker images, binaries, etc.).
- A changelog pipeline to explain what was included in each version.
- Potential release notes that might need to explain to validator changes in their config or particular things to watch out for (e.g. migrations).
- Keep improving and updating validator documentation. (Today, we only have a Notion doc, but we'll probably need a section in our docs).
- What does merging to a branch means (e.g: merging to `main`)

When we start thinking about this, I feel it may be better to transform this GH issue into a full project since it has many angles to cover and requires scoping/discussion. I'm creating the GH issue to capture the need.

**Comment by sanderpick** [comment]
+1 for this. I was just chatting with @joewagner about the possibility of dynamically pulling in builds from GH releases in `local-tableland` vs. building a docker image locally. The added speed would greatly improve that DX.

**Comment by asutula** [comment]
Moving a couple comments from https://www.notion.so/textile/Tableland-Separating-testnet-and-mainnet-networks-f27372c2c43c41a38478b8e0e04abbb1 to here:

- Maybe we consider using different tag formats to trigger deployments to `testnet` and `mainnet`.
- Or we could move away from tags to trigger deployments and use GH Actions instead. I think I prefer this.

**Comment by jsign** [comment]
[See our internal doc proposal](https://www.notion.so/textile/Validator-Releases-Playbook-84f90706d20f487aa3dbbbda3d59d563).
