### ISSUE TITLE
Gather information about read-queries

### ISSUE THREAD

**Issue by jsign** [tablelandnetwork/go-tableland#319]
Today we collect operational (Prometheus) metrics about read-queries, histogram latencies, and similar. We show this in our operational dashboard, which is quite useful.

But I feel we're missing something extra: visibility in outliers. 
Once in a while, I see spikes in the 95-th latency in the `/query` endpoint, which is the result of sometimes a user sending complex/big queries.

It would be useful to know:
- Which are these queries?
- Who is sending these queries, and see if it's worth taking some appropriate action of "banning" per user/IP-address.
- Looking again at our timeouts for read-query execution to put some hard bounds.

Additionally, it might be interesting to simply collect all the read-queries (or do some sampling, but I don't think the volume is that big) so we can understand better how people are using the network to improve their experience or have better focus points. This can be an optional feature to enable in the validator since it has some storage overhead.

cc @sanderpick @brunocalza @carsonfarmer @dtbuchholz

**Comment by brunocalza** [comment]
@jsign picking this for development 

Planning to create a new metric and collect it in both REST and JSON-RPC endpoints (later this one will be gone). Should be straightforward

**Comment by jsign** [comment]
> @jsign picking this for development
> 
> Planning to create a new metric and collect it in both REST and JSON-RPC endpoints (later this one will be gone). Should be straightforward

Cool. Do you have some ideas on what "attributes" will be collected?, like ChainID and TableID.

Regarding the SQL statement per se, I think it might be too heavy to be sent as a metric (or not for a while?), but somehow I think it may be nice to persist them locally so at least they are accessible to the validator? I'm thinking about this if it might be useful to inspect later; not sure.

**Comment by brunocalza** [comment]
> Cool. Do you have some ideas on what "attributes" will be collected?, like ChainID and TableID.

Haven't thought too much. The SQL statement already contains ChainID and TableID, not sure if it is worth the effort to extract them. It can be done at the analysis level, I think. The IP address could be good as you mentioned in your first comment.

> Regarding the SQL statement per se, I think it might be too heavy to be sent as a metric (or not for a while?), but somehow I think it may be nice to persist them locally so at least they are accessible to the validator? I'm thinking about this if it might be useful to inspect later; not sure.

I think we could send them to the metrics server, it shouldn't be a problem. Regarding the local storage, we could start deleting old metrics to avoid the db getting too big.

**Comment by jsign** [comment]
> > Cool. Do you have some ideas on what "attributes" will be collected?, like ChainID and TableID.
> 
> Haven't thought too much. The SQL statement already contains ChainID and TableID, not sure if it is worth the effort to extract them. It can be done at the analysis level, I think. The IP address could be good as you mentioned in your first comment.

Sounds good. Actually the _ChainID_ and _TableID_ are more complicated to extract than I originally thought, since these are read-queries and there might be convoluted situations with JOINS and similar. Sounds good to figure out that at the analysis level (probably we'd need a parser for that, or try some smart ~regexp to get good-enough results).


> > Regarding the SQL statement per se, I think it might be too heavy to be sent as a metric (or not for a while?), but somehow I think it may be nice to persist them locally so at least they are accessible to the validator? I'm thinking about this if it might be useful to inspect later; not sure.
> 
> I think we could send them to the metrics server, it shouldn't be a problem. Regarding the local storage, we could start deleting old metrics to avoid the db getting too big.

SGTM!
