### ISSUE TITLE
[GOT-34] Validate Query against Table structure

### ISSUE THREAD

**Issue by awmuncy** [tablelandnetwork/go-tableland#327]
The Parser currently allows the user to validate a query in isolation, but I'd like to validate that a query will work for a given table. 

I imagine it would work something like this:
```JavaScript
const createTable = "CREATE TABLE MyTable_1_1 (id integer, name text, message text);";
const insertStatement = "INSERT INTO MyTable_1_1 (id, person) VALUES (1, 'Allen');";
parser.validate(createTableStatement, insertStatement); // Returns a failure, since "person" isn't a valid column.
```

An alternative would be to simply instantiate an in-memory database with SQLite, and attempt to run the query against it. For my purposes, I'd have to import sql.js or some other SQLite for browser's solution, into the application or SDK in which I want to validate the query. This adds a lot of overhead for this validation.

<sub>[GOT-34](https://linear.app/tableland/issue/GOT-34/validate-query-against-table-structure)</sub>

**Comment by sanderpick** [comment]
@awmuncy is this issue still a thing?

**Comment by awmuncy** [comment]
No, we can close it.
