### ISSUE TITLE
[GOT-35] Drop JSON-RPC support

### ISSUE THREAD

**Issue by brunocalza** [tablelandnetwork/go-tableland#360]
null

<sub>[GOT-35](https://linear.app/tableland/issue/GOT-35/drop-json-rpc-support)</sub>

**Comment by jsign** [comment]
From what we chatted about yesterday, we'll probably drop support for the current JSON-RPC ~one month after we deploy the new REST APIs. 

I am tagging this on-hold since it would be detached/defered from the project dates.

cc @carsonfarmer @brunocalza
