### ISSUE TITLE
How to use `--dir` flag?

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/go-tableland#378]
I've been successfully building and running this repo with the goal of finishing https://github.com/orgs/tablelandnetwork/projects/36
But passing in the location of the config.json file with the `--dir` flag always results in `flag provided but not defined: -dir`

### Steps to reproduce

1. build with `BIN_BUILD_FLAGS="GOOS=darwin" make build-api-debug`.  I also tried `BIN_BUILD_FLAGS="GOOS=linux" make build-api-debug`
2. run the output of the build with `./api --dir <non-default path to config>`

I'm working on a intel Mac with Big Sur 11.5.2
go version go1.19.1 darwin/amd64
make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0

### What I've tried

If I change the default value of the dir flag to the path of my local machine and do *not* include the flag when running, everything works fine.  However my current thinking would require the path to the config is specific to the machine running the validator.

I searched for similar issues and found a suggestion `flag.Parse()` is being called before the flag is defined, but the only useage of the flag package I can find is the origin of the error: https://github.com/tablelandnetwork/go-tableland/blob/main/cmd/api/config.go#L114-L140

I suspect that the problem is either me making a simple mistake, or something to do with the go uconfig package.
Any help would be greatly appreciated

**Comment by brunocalza** [comment]
Thanks, @joewagner for opening this. I'm trying to figure out what's going on. It looks like `uconfig` is expecting `dir` to be defined in the `config` struct.

**Comment by joewagner** [comment]
> Thanks, @joewagner for opening this. I'm trying to figure out what's going on. It looks like `uconfig` is expecting `dir` to be defined in the `config` struct.

Yeah, that seems like whats happening.  My limited understanding is that uconfig constructs the configuration by combining env vars, command flags, and a config file.  I think that means that if we specify the config file location as a flag (or ENV) uconfig is going to enforce that the location of the config __is__ part of the config.  Which seems strange  to me, but I'm not sure.

**Comment by joewagner** [comment]
I you insert `Dir string` as line 21 in cmd/api/config.go everything works.  That feels a bit hacky to me though

**Comment by brunocalza** [comment]
@joewagner Try adding to the [`config` struct](https://github.com/tablelandnetwork/go-tableland/blob/main/cmd/api/config.go#L20): `Dir  string `default:""``, and see how far you can get

**Comment by joewagner** [comment]
> @joewagner Try adding to the [`config` struct](https://github.com/tablelandnetwork/go-tableland/blob/main/cmd/api/config.go#L20): `Dir string `default:""``, and see how far you can get

Everything works if I do that.  Does that seem ok to you?

**Comment by brunocalza** [comment]
Feels hacky. But maybe that's how `uconfig` works. For every flag, you pass you must have a definition. I'll check if that's the case. And we don't get an error in our current way of running things because we rely on the default.

**Comment by joewagner** [comment]
> Feels hacky. But maybe that's how `uconfig` works. For every flag, you pass you must have a definition. I'll check if that's the case. And we don't get an error in our current way of running things because we rely on the default.

@brunocalza Works for me, I'll create a PR
