### ISSUE TITLE
How to correctly use local-down?

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/go-tableland#404]
I was looking at a fix for https://github.com/tablelandnetwork/local-tableland/issues/48 and can't seem to get `make local-down` to work how I thought it would.

### What I've done

1. Start a hardhat evm node and deploy a registry contract to it.
2. In this repo run `cd docker && make local-up`.  The Validator starts correctly and seems to work as expected.
3. From a second terminal window in this repo run `cd docker && make local-down`.  This produces some warnings and an error, show below.

### What happens

```
WARN[0000] The "PLATFORM" variable is not set. Defaulting to a blank string. 
WARN[0000] The "BOOTSTRAP_BACKUP_URL" variable is not set. Defaulting to a blank string. 
WARN[0000] The "ENVIRONMENT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "ENVIRONMENT" variable is not set. Defaulting to a blank string. 
open /Users/jwagner/Workspaces/textile/github/go-tableland/docker//api/.env_validator: no such file or directory
make: *** [local-down] Error 14
```

Issue [#48](https://github.com/tablelandnetwork/local-tableland/issues/48) isn't really causing any problems and we could close it with `won't fix` if there isn't an easy solution for this, but wanted to make sure I'm not missing something obvious.

**Comment by jsign** [comment]
@joewagner, do you mind trying this draft PR https://github.com/tablelandnetwork/go-tableland/pull/406? I did some tuning to avoid those warnings.

**Comment by joewagner** [comment]
> @joewagner, do you mind trying this draft PR #406? I did some tuning to avoid those warnings.

That fix is perfect, thanks again
