### ISSUE TITLE
[GOT-53] darwin arm64 binaries

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/go-tableland#463]
@brunocalza @joewagner I know it was decided to skip darwin arm64 builds for the time being, but I recently (randomly) came across a tool that might help with builds targeting darwin arm64: https://github.com/goreleaser/goreleaser-cross ("Docker container to turn CGO cross-compilation pain into a pleasure"). 

here's an example: https://github.com/suborbital/e2core/pull/201

<sub>[GOT-53](https://linear.app/tableland/issue/GOT-53/darwin-arm64-binaries)</sub>

**Comment by joewagner** [comment]
Looks promising!
