### ISSUE TITLE
[GOT-4] Replace `mux` package with a currently maintained project.

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/go-tableland#510]
<sub>From [SyncLinear.com](https://synclinear.com) | [GOT-4](https://linear.app/tableland/issue/GOT-4/replace-mux-package-with-a-currently-maintained-project)</sub>

**Comment by joewagner** [comment]
yep, so much!

**Comment by joewagner** [comment]
I was a bit overloaded this cycle, I'm gonna have to move this to cycle 2

**Comment by joewagner** [comment]
Note: we will use chi to replace mux.

**Comment by joewagner** [comment]
Perfect, Thanks!

**Comment by joewagner** [comment]
If you branch off from `joe/rm-relay` you should be fine. With that we can release the JSON-RPC drop and the new routing library in one go.

**Comment by joewagner** [comment]
@brunocalza There is a lot of potential for merge conflicts with the branch that has the JSON-RPC changes if I do the updates to change the mux package to chi.  I'm planning to wait until after JSON-RPC removal work is most of the way complete to start on that.  Does that make sense to you?

**Comment by sanderpick** [comment]
@joewagner should we move this one to cycle 3?
