### ISSUE TITLE
[GOT-92] The Validator API endpoint to get a transaction receipt returns `table_id`, when there is potentially many tables associated with a transaction.

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/go-tableland#522]
We should consider changing the schema of the JSON data returned from /receipt/{chainId}/{transactionHash} to allow sending back all of the table IDs associated with the transaction.

Specifically this line would need to change from `type: string` to `type: array` with `items` as `type: string`.

[https://github.com/tablelandnetwork/docs/blob/main/specs/validator/tableland-openapi-spec.yaml#L248](https://github.com/tablelandnetwork/docs/blob/main/specs/validator/tableland-openapi-spec.yaml#L248)

The underlying system database table, `system_txn_receipts`, may or may not need to change.  We could potentially change the `table_id` column to accommodate a list of IDs, or perhaps we could insert a row for each unique combination of chain_id, txn_hash, and table_id.  This might already be how the table was designed?

I've marked this as a bug, but maybe it should be a feature request.  My thinking is that since we have been supporting transactions that support mutating more than one table since August 2022, we should have been returning all of the table IDs. However the only way to create this type of transaction was via direct contract to contract interaction with the Registry, and maybe aquiring all of the table IDs is a feature?

<sub>From [SyncLinear.com](https://synclinear.com) | [GOT-92](https://linear.app/tableland/issue/GOT-92/[got-93]-the-validator-api-endpoint-to-get-a-transaction-receipt)</sub>

**Comment by brunocalza** [comment]
@joewagner let me know how urgent this is

**Comment by sanderpick** [comment]
@brunocalza is this fixable this week by chance? it would be nice to release the batch write functionality soon.

**Comment by brunocalza** [comment]
Looks like the fix here is an API breaking change. The ideal scenario would be to have a new API version that fixes this while supporting the old one, so we don't break any clients. We should probably create a project for that we plan properly. Trying to sneak in a breaking change in the middle of releases is certainly not a good idea. 

To unblock us in the meantime I suggested @joewagner to query the `system_txn_receipts` table directly using the `query` API. That should work. @joewagner is going to confirm if that really works. 

wdyt @sanderpick ? 

cc  @carsonfarmer

**Comment by carsonfarmer** [comment]
Yeh this seems like a reasonable compromise. In the mean time, we certainly *should* create a project for this and get it into the planning pipeline.

**Comment by joewagner** [comment]
> * i'm guessing this is the original issue and it was created from linear?

Yep, I created this via Linear. I'm not sure what happened. 
I put the public tag on it after I created the issue, not sure if that would make any difference.

> * looks like the description was changed… did you do that from linear or github?

I've only edited the description via Linear.

**Comment by sanderpick** [comment]
k, thanks. odd… i'll have to keep digging

**Comment by sanderpick** [comment]
I deleted the duplicate issue. Pasting comment here from @brunocalza: 

> Looks like the fix here is an API breaking change. The ideal scenario would be to have a new API version that fixes this while supporting the old one, so we don't break any clients. We should probably create a project for that we plan properly. Trying to sneak in a breaking change in the middle of releases is certainly not a good idea. 
>
> To unblock us in the meantime I suggested @joewagner to query the `system_txn_receipts` table directly using the `query` API. That should work. @joewagner is going to confirm if that really works.

**Comment by sanderpick** [comment]
okay guys, here's a project: [https://linear.app/tableland/project/multi-table-batch-writes-fab3fab05ea4](https://linear.app/tableland/project/multi-table-batch-writes-fab3fab05ea4). I added the ship issues to cycle 3b, and the work to cycle 3. is that enough time to get this sorted?

**Comment by sanderpick** [comment]
(I moved the work issues from Tooling Table Stakes to that project as well)

**Comment by brunocalza** [comment]
I won't be around for half of the the cycle 3, but one week is probably good enough. The major blocker is deciding on the API spec and things like: should we bump the API version, should we simply create a new method then later remove the old one? Or should we version the method itself?

Thinking a bit about the most reasonable API spec for this case should not be hard, but it's really important. It's thinking strategically how we evolve our APIs. For example, is this good enough of a change to bump the version? What are the implications of bumping a version? We don't want our new API evolving in a clunky way again 😅 

With that out of the way, it should be quick.

**Comment by sanderpick** [comment]
We use semver—the answer is pretty easy:

* Breaking changes are major version bumps
* New features are minor bumps
* Fixes / improvements that don't touch the public API are patch bumps

Other notes:

* We should always keep two versions live: The current version and the previous version.
* We should add versioning to the docs (cc @dtbuchholz) where the current version is the default `/` but you can always go to `/v1`, `/v2`, etc.
* We should make sure our Accept Header includes version info.

Anything else?

**Comment by sanderpick** [comment]
Nice! tbh, now that the site is live and looking so good, we may as stick with docusaurus esp. if they have versioning support built it. so +1 for option 2.

**Comment by joewagner** [comment]
FYI: I'm finished implementing the SDK changes that prompted me to open this issue.  The SDK works well, so this is not blocking anything at the moment.

**Comment by sanderpick** [comment]
Just to clarify, are we planning on a major version bump w/ the release of the multi-table batch writes? ie, is that validator API changing?

**Comment by joewagner** [comment]
> Just to clarify, are we planning on a major version bump w/ the release of the multi-table batch writes? ie, is that validator API changing?

The multi-table batch writes don't require any changes to the Validator api at the moment.  From the client perspective, we can wait on this change as long as needed

**Comment by brunocalza** [comment]
So, since this is not a blocker, what should we do with this issue? Work on it now or put in the backlog? (reminding that working on this comes with more work to update clients and docs because of api bump )

**Comment by joewagner** [comment]
> So, since this is not a blocker, what should we do with this issue? Work on it now or put in the backlog? (reminding that working on this comes with more work to update clients and docs because of api bump )

No strong opinion.  Maybe leave the issue open, and make sure this change is included in the next major api version?

**Comment by sanderpick** [comment]
@joewagner your client-side solution… does it work by making multiple requests and packaging up a receipt that contains multiple tables?

my vote would be to use this as a forcing function to get versioning going in the docs, and to flex the major version bump muscle before bigger changes.

**Comment by joewagner** [comment]
> @joewagner your client-side solution… does it work by making multiple requests and packaging up a receipt that contains multiple tables?

No, the client can get the tableId from the contract receipt which is already being return from the contract call.  At the moment typescript users _might_ have have a problem with our typings, because we use `any` for a return type.  However, I don't have anyway to confirm that and no one has reported anything.

**Comment by brunocalza** [comment]
> my vote would be to use this as a forcing function to get versioning going in the docs, and to flex the major version bump muscle before bigger changes.

sounds good! i work on this then

**Comment by brunocalza** [comment]
@joewagner 

As I was working on this today, I understood the real nature of the problem and realized we don't really need an API bump. At first I thought the fields `table_id`, `error` and `error_event_idx` were all wrong, and the correct solution would be to return an array of receipts, thus breaking the API. 

But the problem is only in the `table_id` fields. It must be an `array` and not `string`, as you said. 

I think the cleanest solution is to simply add a new field `table_ids` and deprecate the `table_id`. With that we would not break the API, without the need to bump version.

Take a look at the spec change [https://github.com/tablelandnetwork/docs/pull/112/files](https://github.com/tablelandnetwork/docs/pull/112/files) and the validator change [https://github.com/tablelandnetwork/go-tableland/pull/549/files](https://github.com/tablelandnetwork/go-tableland/pull/549/files) and see if that makes sense. 

And reflecting on this now it all makes sense. A transaction should only have one receipt independently of how many events it processes or how many tables it touches. And having an array of errors does not make sense, because we process events serially, which means when an error occurs that a particular event, that's the error the goes to the receipt. 

Let me know if that makes sense

**Comment by joewagner** [comment]
@brunocalza That makes sense to me.  The SDK only expects one reciept to come back, but the receipt would have all the affected tableIds.
Your spec changes look good, and when your PR is rfr I can do some testing to make sure the SDK, CLI, etc... are all backward compatable.

**Comment by brunocalza** [comment]
rfr @joewagner

**Comment by joewagner** [comment]
@brunocalza Looking what needs to happen with the new spec to get integrated into the JS-SDK now.  I'll look at the Validator changes next.
