### ISSUE TITLE
[GOT-94] test test

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/go-tableland#525]
foo

<sub>From [SyncLinear.com](https://synclinear.com) | [GOT-94](https://linear.app/tableland/issue/GOT-94/test-test)</sub>

**Comment by sanderpick** [comment]
@brunocalza the syncing seems to be working fine for me. I'm curious, @joewagner do you by chance not have a sync setup on go-tableland?

**Comment by sanderpick** [comment]
I'm going to try another test where the public label is added after linear issue is created.

**Comment by joewagner** [comment]
> @brunocalza the syncing seems to be working fine for me. I'm curious, @joewagner do you by chance not have a sync setup on go-tableland?

@sanderpick I do have it setup.
