### ISSUE TITLE
[GOT-101] [GOT-100] Validator release workflow doesn't connect to js-validator after upgrade to `goreleaser`

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/go-tableland#535]
The update to use goreleaser to build binaries works well within go-tableland, but the automated js-validator pull requests aren't able to include the new builds because the binary name includes a shortened commit hash in the name.

Since js-validator doesn't know how to get the name of the zipped binary it can't download the file.

I'll submit a PR with a fix that uses the old naming scheme.  If having the commit hash in the name is important, we can explore alternatives.

<sub>From [SyncLinear.com](https://synclinear.com) | [GOT-100](https://linear.app/tableland/issue/GOT-100/validator-release-workflow-doesnt-connect-to-js-validator-after)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [GOT-100](https://linear.app/tableland/issue/GOT-100/validator-release-workflow-doesnt-connect-to-js-validator-after)</sub>

**Comment by sanderpick** [comment]
bummer. very odd that it only happens once in a while. i mean, looking at the code of the sync app i'm not surprised… it's spaghetti town. if it starts to happen w/ high freq i can look into it some more.

**Comment by joewagner** [comment]
This should be fixed now, but we will find out when the release happens today.

**Comment by joewagner** [comment]
fixed by #536
