### ISSUE TITLE
[GOT-102] Update README

### ISSUE THREAD

**Issue by dtbuchholz** [tablelandnetwork/go-tableland#539]
**About:** 

Go implementation of the Tableland database - run your own node, handling on-chain events and serving read-queries

**Intro**:

go-tableland is a Go language implementation of a Tableland node, enabling developers and service providers to run nodes on the Tableland network and host databases for web3 users and applications. Note: the Tableland protocol is currently in open beta, so node operators have the opportunity to be one of the early network adopters.

<sub>From [SyncLinear.com](https://synclinear.com) | [GOT-102](https://linear.app/tableland/issue/GOT-102/update-readme)</sub>

**Comment by sanderpick** [comment]
we should get this one done for sure. the readme is quite old
